# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebef52fb42a2a17842e29a3cabb4235a"
name = "ehf-manager"
application_url = "https://ehf-manager.onrender.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders"

[auth]
redirect_urls = [
  "https://ehf-manager.onrender.com/auth/callback",
  "https://ehf-manager.onrender.com/auth/shopify/callback",
  "https://ehf-manager.onrender.com/api/auth/callback"
]

[pos]
embedded = false
